apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-init-common-pv
  labels:
    prophecy.io/cluster: prophecy
    prophecy.io/component: nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 128Gi
  mountOptions:
    - hard
  nfs:
    path: /export/prophecy
    server: 172.20.44.233
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  volumeMode: Filesystem
