apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitserver-log-volume-prophecy
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  mountOptions:
    - hard
  nfs:
    path: /export/prophecy_gitlog
    server: 172.20.44.233
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  volumeMode: Filesystem

