apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-log-volume-prophecy
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  mountOptions:
    - hard
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: <replace_with_path_on_nfs_server>
    server: <replace_with_nfs_server_ip>
  storageClassName: nfs
  volumeMode: Filesystem

