apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-log-volume-prophecy
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  mountOptions:
    - hard
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /export/prophecy_pglog
    server: 172.20.44.233
  storageClassName: nfs
  volumeMode: Filesystem

