apiVersion: prophecy.simpledatalabs.inc/v1
kind: ProphecyDataPlane
metadata:
  name: prophecy
spec:
  name: prophecy
  namespace: prophecy
  tenant_name: prophecy
  customer_name: visa
  team: ""
  disable_fluentbit_sidecar: true
  path-prefix: "/storage"
  spark_execution_provider: ""
  databricks_url: ""
  databricks_org_id: ""
  databricks_prophecy_jar_path: ""
  databricks_token: ""
  enabledapps: execution,pkg_manager,sparkhistory
  postgres_host: postgres
  bootup:
    nodeSelector:
      pharos.io/pke-nodepool: default
    tolerations:
      - effect: NoSchedule
        key: pharos.io/pke-nodepool
        operator: Equal
        value: default
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    bootup-volume:
      volumename: nfs-init-common-pv
  execution:
    image: prophecy/execution:latest
    nodeSelector:
      pharos.io/pke-nodepool: default
    tolerations:
      - effect: NoSchedule
        key: pharos.io/pke-nodepool
        operator: Equal
        value: default
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "2"
        memory: 4Gi
    execution_url: http://execution.stage.visa.com
    metagraph_host: metagraph.stage.visa.com
    codegen_host: cgweb.stage.visa.com
    sparkedge_host: sparkedge.stage.visa.com
    metagraph_port: 80
    codegen_port: 80
    sparkedge_port: 80
    # Check why are we passing url like this. It can be accessed on internal network too.
    sparkhistory_url: http://sparkhistory.stage.visa.com
  pkg_manager:
    image: prophecy/pkg-manager:latest
    nodeSelector:
      pharos.io/pke-nodepool: default
    tolerations:
      - effect: NoSchedule
        key: pharos.io/pke-nodepool
        operator: Equal
        value: default
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
  sparkhistory:
    image: prophecy/spark-history:latest
    nodeSelector:
      pharos.io/pke-nodepool: default
    tolerations:
      - effect: NoSchedule
        key: pharos.io/pke-nodepool
        operator: Equal
        value: default
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
  externalstorage:
    storagetype: nfs
    storageclassname: nfs
    base-vol-name: cp-shared-vol

