apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-init-common-pv
  labels:
    prophecy.io/cluster: prophecy
    prophecy.io/component: nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 128Gi
  mountOptions:
    - hard
  nfs:
    path: "<replace_with_path_on_nfs_server>"
    server: <replace_with_nfs_server_ip>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  volumeMode: Filesystem
