apiVersion: v1
kind: PersistentVolume
metadata:
  name: metagraph-projectrepos-hp-volume-prophecy
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "<replace_with_path_on_hostpath>"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: localpath
  volumeMode: Filesystem
