apiVersion: apps/v1
kind: Deployment
metadata:
  name: prophecy-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: prophecy
      name: prophecy-operator
      release: prophecy
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: prophecy
        name: prophecy-operator
        release: prophecy
    spec:
      serviceAccountName: prophecy-operator
      securityContext:
        runAsUser: 1001
      nodeSelector:
        pharos.io/pke-nodepool: default
      tolerations:
      - effect: NoSchedule
        key: pharos.io/pke-nodepool
        operator: Equal
        value: default
      containers:
        - name: prophecy-operator
          image: prophecy/prophecy-operator:latest
          imagePullPolicy: Always
          ports:
            - name: metrics
              containerPort: 8383
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: prophecy-operator

