apiVersion: apps/v1
kind: Deployment
metadata:
  name: prophecy-dataplane-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: prophecy
      name: prophecy-dataplane-operator
      release: prophecy
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: prophecy
        name: prophecy-dataplane-operator
        release: prophecy
    spec:
      serviceAccountName: prophecy-dataplane-operator
      imagePullSecrets:
        - name:  <replace_with_secret_of_visa_repo>
      securityContext: {}
      containers:
        - name: prophecy-dataplane-operator
          image:  <replace_with_dataplane_operator_image_in_visa_repo>
          imagePullPolicy: Always
          ports:
            - name: metrics
              containerPort: 8383
          resources: {}
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: prophecy-dataplane-operator

