apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-init-common-pv
  labels:
    prophecy.io/cluster: prophecy
    prophecy.io/component: nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 128Gi
  mountOptions:
    - hard
  nfs:
    path: "/pharos_484/prophecy"
    server: SU73ISIDEV02NPBN.corpdev.visa.com
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  volumeMode: Filesystem
