apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitserver-hp-volume-prophecy
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/ssadfs-a/sphinx/stage/prophecy/gitdata"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: localpath
  volumeMode: Filesystem
