apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitserver-log-volume-prophecy
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  mountOptions:
    - hard
  nfs:
    path: "/pharos_484/prophecy"
    server: SU73ISIDEV02NPBN.corpdev.visa.com
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  volumeMode: Filesystem
