apiVersion: v1
kind: PersistentVolume
metadata:
  name: metagraph-projectrepos-hp-volume-prophecy
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/ssadfs-a/sphinx/stage/prophecy/projectrepos"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: localpath
  volumeMode: Filesystem
