{
 "title": "Kamon 2.0 Akka",
 "description": "Kamon 2.0 and Akka Dashboard using Prometheus as Datasource",
 "tags": [
  "Kamon",
  "Akka",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "percentile", "label": "Percentile", "query": "0.5,0.90,0.95,0.99,0.999" },
   {
    "name": "job",
    "query": "label_values(akka_system_unhandled_messages_total, job)"
   }
  ]
 },
 "panels": [
  { "title": "Akka System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unhandled Messages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum(rate(akka_system_unhandled_messages_total{job=~\"$job\"}[$interval])) by (job)"
    }
   ]
  },
  {
   "title": "Dead Letters",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(akka_system_dead_letters_total{job=~\"$job\"}[$interval])) by (job)"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(akka_system_active_actors_count{job=~\"$job\"}[$interval])) by (job)",
     "legendFormat": "Active Actors"
    },
    {
     "expr": "sum(irate(akka_system_processed_messages_total{tracked=\"true\", job=~\"$job\"}[$interval])) by (job)",
     "legendFormat": "Processed Messages (tracked=true)"
    },
    {
     "expr": "sum(irate(akka_system_processed_messages_total{tracked=\"false\", job=~\"$job\"}[$interval])) by (job)",
     "legendFormat": "Processed Messages (tracked=false)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "akka_group_errors_total", "legendFormat": "{{group}}" }
   ]
  },
  { "title": "Akka Http Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Processing Time ($percentile)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(span_processing_time_seconds_bucket{job=~\"$job\"}[$interval])) by (le,operation,span_kind,error)) * 1000",
     "legendFormat": "{{ span_kind }}:{{ operation }} (error={{ error }})"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_request_active_sum{job=~\"$job\"}[$interval]) / rate(http_server_request_active_count{job=~\"$job\"}[$interval])",
     "legendFormat": "{{ job }}: {{ interface }}:{{ port }}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_connection_open_sum{job=~\"$job\"}[$interval]) / rate(http_server_connection_open_count{job=~\"$job\"}[$interval])",
     "legendFormat": "{{ job }}: {{ interface }}:{{ port }}"
    }
   ]
  },
  { "title": "Akka Group Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Processing Time ($percentile)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(akka_group_processing_time_seconds_bucket{job=~\"$job\"}[$interval])) by (le, group)) * 1000",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Time in Mailbox ($percentile)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(akka_group_time_in_mailbox_seconds_bucket{job=~\"$job\"}[$interval])) by (le, group))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Mailbox Size / Number of Members",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(akka_group_mailbox_size_sum{job=~\"$job\"}[$interval]) / rate(akka_group_mailbox_size_count{job=~\"$job\"}[$interval])",
     "legendFormat": "{{group}} mailbox"
    },
    {
     "expr": "rate(akka_group_members_sum{job=~\"$job\"}[$interval]) / rate(akka_group_members_count{job=~\"$job\"}[$interval])",
     "legendFormat": "members of {{group}} "
    }
   ]
  },
  { "title": "Executor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Number Of Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(executor_threads_total_count{job=~\"$job\"}[$interval]) / rate(executor_threads_total_sum{job=~\"$job\"}[$interval])",
     "legendFormat": "System:{{akka_system}} - Name: {{name}} - Type: {{type}}"
    }
   ]
  },
  {
   "title": "Number Of Tasks Completed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(executor_tasks_completed_total{job=~\"$job\"}[$interval])",
     "legendFormat": "{{ job }}: {{ name }} ({{ type }}) {{akka_system}}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(executor_queue_size_bucket{job=~\"$job\", le=\"+Inf\"}[$interval])",
     "legendFormat": "{{ akka_system }}: {{ name }} ({{ type }})"
    }
   ]
  },
  {
   "title": "Maximum Number of Threads",
   "type": "graph",
   "description": "Tracks executor maximum number of Threads",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "executor_threads_max{job=~\"$job\"}",
     "legendFormat": "System: {{akka_system}} - Name: {{name}} - Type: {{type}}"
    }
   ]
  },
  {
   "title": "Minimum Number of Threads",
   "type": "graph",
   "description": "Tracks executor minimum number of Threads",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "executor_threads_min{job=~\"$job\"}",
     "legendFormat": "System: {{akka_system}} - Name: {{name}} - Type: {{type}}"
    }
   ]
  },
  {
   "title": "Executor parallelism",
   "type": "graph",
   "description": "Tracks executor parallelism",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "executor_parallelism{job=~\"$job\"}",
     "legendFormat": "System: {{akka_system}} - Name: {{name}} - Type: {{type}}"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Garbage Collection",
   "type": "graph",
   "description": "Tracks the distribution of GC events duration",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_seconds_sum{job=~\"$job\"}[2m])/rate(jvm_gc_seconds_count{ job =~\"$job\"}[2m])",
     "legendFormat": " {{job}}  GC count: {{collector}}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{job=~\"$job\", region=\"heap\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_committed_bytes{job=~\"$job\", region=\"heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_used_bytes_sum{job=~\"$job\", region=\"heap\"} / jvm_memory_used_bytes_count{job=~\"$job\", region=\"heap\"}",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Host Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Free Memory",
   "type": "graph",
   "description": "Tracks the amount of free memory",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 68 },
   "format": "decbytes",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "host_memory_free_bytes{job=~\"$job\"}",
     "legendFormat": "Free Memory"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "graph",
   "description": "Tracks the total memory available vs  the amount of used memory\n",
   "gridPos": { "h": 5, "w": 10, "x": 3, "y": 68 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "host_memory_used_bytes{job=~\"$job\"}",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "host_memory_total_bytes{job=~\"$job\"}",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "graph",
   "description": "Tracks the system load average",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "host_load_average{job=~\"$job\", period=\"1m\"}",
     "legendFormat": "host load average"
    }
   ]
  },
  {
   "title": "Free Swap Memory",
   "type": "graph",
   "description": "Tracks the free Swap space",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 73 },
   "format": "bytes",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "host_swap_free_bytes{job=~\"$job\"}",
     "legendFormat": "Free Swap Memory"
    }
   ]
  },
  {
   "title": "Swap Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 3, "y": 73 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "host_swap_used_bytes{job=~\"$job\"}",
     "legendFormat": "Used Swap Memory"
    },
    {
     "expr": "host_swap_total_bytes{job=~\"$job\"}",
     "legendFormat": "Total Swap Memory"
    }
   ]
  }
 ]
}