apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prophecy-dataplane-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - dataplane-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs:
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - replicasets
      - deployments
    verbs:
      - get
  - apiGroups:
      - prophecy.simpledatalabs.inc
    resources:
      - '*'
      - prophecydataplanes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prophecy-dataplane-operator
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prophecy-dataplane-operator
subjects:
  - kind: ServiceAccount
    name: prophecy-dataplane-operator
    namespace: prophecy
roleRef:
  kind: Role
  name: prophecy-dataplane-operator
  apiGroup: rbac.authorization.k8s.io

